name: torch
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.3.1=pyhd8ed1ab_0
  - blosc=1.21.6=hfd34d9b_1
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.8.3=h4c7d964_0
  - expat=2.7.1=h8ddb27b_0
  - freexl=2.0.0=hf297d47_2
  - gdal=3.11.3=py310h2ed3b37_2
  - geos=3.13.1=h9ea8674_0
  - grpcio=1.74.0=py310hc77e67f_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2024.2.1=h57928b3_1083
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarchive=3.8.1=gpl_h1ca5a36_100
  - libblas=3.9.0=32_h641d27c_mkl
  - libbrotlicommon=1.1.0=h2466b09_3
  - libbrotlidec=1.1.0=h2466b09_3
  - libbrotlienc=1.1.0=h2466b09_3
  - libcblas=3.9.0=32_h5e41251_mkl
  - libcurl=8.14.1=h88aaa65_0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgcc=15.1.0=h1383e82_4
  - libgdal-core=3.11.3=hddc0a0b_2
  - libgomp=15.1.0=h1383e82_4
  - libgrpc=1.74.0=h04afb49_0
  - libhwloc=2.12.1=default_h88281d1_1000
  - libhwy=1.2.0=h1d1702c_0
  - libiconv=1.18=h135ad9c_1
  - libjpeg-turbo=3.1.0=h2466b09_0
  - libjxl=0.11.1=ha161b08_2
  - libkml=1.3.0=h538826c_1021
  - liblapack=3.9.0=32_h1aa476e_mkl
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_1
  - libre2-11=2025.07.22=h0eb2380_0
  - librttopo=1.1.0=hbfc9ebc_18
  - libspatialite=5.1.0=h378fb81_14
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.0=h05922d8_5
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h741aa76_1
  - libzlib=1.3.1=h2466b09_2
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - markdown=3.8.2=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310h38315fa_1
  - minizip=4.0.10=h9fa1bad_0
  - mkl=2024.2.2=h66d3029_15
  - muparser=2.3.5=he0c23c2_0
  - numpy=2.2.6=py310h4987827_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.5.2=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.45=h99c9b8b_0
  - pillow=11.3.0=py310h6d647b9_0
  - pip=25.1=pyhc872135_2
  - proj=9.6.2=h7990399_1
  - protobuf=6.31.1=py310h81b7714_0
  - pthread-stubs=0.4=h0e40799_1002
  - python=3.10.18=h8c5b53a_0_cpython
  - python_abi=3.10=8_cp310
  - re2=2025.07.22=h3dd2b4f_0
  - setuptools=78.1.1=py310haa95532_0
  - snappy=1.2.2=h7fa0ca8_0
  - sqlite=3.50.2=hda9a48d_1
  - tbb=2021.13.0=h18a62a1_2
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py310h5588dad_2
  - tk=8.6.13=h2c6b04d_2
  - ucrt=10.0.22621.0=haa95532_0
  - uriparser=0.9.8=h5a68840_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py310haa95532_0
  - xerces-c=3.2.5=he0c23c2_2
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_2
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - accelerate==1.10.1
      - affine==2.4.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - calflops==0.3.2
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.3.0
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - colorama==0.4.6
      - comet-ml==3.52.1
      - configobj==5.0.9
      - contourpy==1.3.2
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - decorator==5.2.1
      - dulwich==0.24.1
      - einops==0.8.1
      - everett==3.1.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastrlock==0.8.3
      - filelock==3.18.0
      - fonttools==4.59.2
      - fsspec==2025.7.0
      - ftfy==6.3.1
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h5py==3.14.0
      - huggingface-hub==0.34.4
      - idna==3.10
      - imageio==2.37.0
      - iopath==0.1.10
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - llvmlite==0.45.1
      - markdown-it-py==4.0.0
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - medpy==0.5.2
      - ml-collections==1.1.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - numba==0.62.1
      - nvidia-ml-py==13.580.82
      - openai-clip==1.0.1
      - opencv-python==4.12.0.88
      - panda==0.3.1
      - pandas==2.3.2
      - parso==0.8.5
      - polars==1.33.1
      - portalocker==3.2.0
      - prefetch-generator==1.0.3
      - prompt-toolkit==3.0.52
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywin32==311
      - pyyaml==6.0.2
      - rasterio==1.4.3
      - referencing==0.36.2
      - regex==2025.9.18
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.1.0
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - segformer-pytorch==0.0.6
      - semantic-version==2.10.0
      - sentry-sdk==2.37.1
      - simpleitk==2.5.2
      - simplejson==3.20.1
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboardx==2.6.4
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.20
      - tokenizers==0.22.1
      - torch==2.5.1+cu124
      - torchvision==0.20.1+cu124
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.56.2
      - triton==3.1.0
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - ultralytics==8.3.198
      - ultralytics-thop==2.0.17
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - wrapt==1.17.3
      - wurlitzer==3.1.1
      - yacs==0.1.8
prefix: D:\anaconda3\envs\torch
